In [53]:
from bs4 import BeautifulSoup
from selenium import webdriver
from urllib import request

In [54]:
url = "http://www.kasen-suibo.metro.tokyo.jp/im/uryosuii/tsim0105g_1H14.html"

In [55]:
html = request.urlopen(url)

In [56]:
soup = BeautifulSoup(html, "html.parser")

In [57]:
table = soup.findAll("table")

In [59]:
table

[<table border="0" cellpadding="0" cellspacing="0" id="uryo-suii-dataTb">
 <tr>
 <th scope="row">観測日時</th>
 <td>20:42</td>
 <td>20:43</td>
 <td>20:44</td>
 <td>20:45</td>
 <td>20:46</td>
 <td>20:47</td>
 <td>20:48</td>
 <td>20:49</td>
 <td>20:50</td>
 <td>20:51</td>
 <td>20:52</td>
 <td>20:53</td>
 </tr>
 <tr>
 <th scope="row">1分間雨量</th>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 </tr>
 <tr>
 <th scope="row">累計雨量</th>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 </tr>
 <tr>
 <th scope="row">時間最大雨量</th>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 </tr>
 </table>,
 <table border="0" cellpadding="0" cellspacing="0" id="uryo-suii-dataTb">
 <tr>
 <th scope="row">観測日時</th>
 <td>20:54</td>
 <td>20:55</td>
 <td>20:56</td>
 <td>20:57</td>
 <td>20:58</td>
 <td>20:59</td>
 <td>21:00</td>
 <td>21:01</td>
 <td>21:02</td>
 <td>21:03</td>
 <td>21:04</td>
 <td>21:05</td>
 </tr>
 <tr>
 <th scope="row">1分間雨量</th>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 </tr>
 <tr>
 <th scope="row">累計雨量</th>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 </tr>
 <tr>
 <th scope="row">時間最大雨量</th>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 </tr>
 </table>,
 <table border="0" cellpadding="0" cellspacing="0" id="uryo-suii-dataTb">
 <tr>
 <th scope="row">観測日時</th>
 <td>17:10</td>
 <td>17:20</td>
 <td>17:30</td>
 <td>17:40</td>
 <td>17:50</td>
 <td>18:00</td>
 <td>18:10</td>
 <td>18:20</td>
 <td>18:30</td>
 <td>18:40</td>
 <td>18:50</td>
 <td>19:00</td>
 </tr>
 <tr>
 <th scope="row">10分間雨量</th>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 </tr>
 <tr>
 <th scope="row">累計雨量</th>
 <td>
        						9
      						</td>
 <td>
        						9
      						</td>
 <td>
        						9
      						</td>
 <td>
        						9
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 </tr>
 <tr>
 <th scope="row">時間最大雨量</th>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 </tr>
 </table>,
 <table border="0" cellpadding="0" cellspacing="0" id="uryo-suii-dataTb">
 <tr>
 <th scope="row">観測日時</th>
 <td>19:10</td>
 <td>19:20</td>
 <td>19:30</td>
 <td>19:40</td>
 <td>19:50</td>
 <td>20:00</td>
 <td>20:10</td>
 <td>20:20</td>
 <td>20:30</td>
 <td>20:40</td>
 <td>20:50</td>
 <td>21:00</td>
 </tr>
 <tr>
 <th scope="row">10分間雨量</th>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td class="bkText-red">
        						0
      						</td>
 <td class="bkText-red">
        						0
      						</td>
 <td class="bkText-red">
        						0
      						</td>
 <td class="bkText-red">
        						0
      						</td>
 <td class="bkText-red">
        						0
      						</td>
 <td class="bkText-red">
        						0
      						</td>
 </tr>
 <tr>
 <th scope="row">累計雨量</th>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td class="bkText-red">
        						0
      						</td>
 <td class="bkText-red">
        						0
      						</td>
 <td class="bkText-red">
        						0
      						</td>
 <td class="bkText-red">
        						0
      						</td>
 <td class="bkText-red">
        						0
      						</td>
 <td class="bkText-red">
        						0
      						</td>
 </tr>
 <tr>
 <th scope="row">時間最大雨量</th>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td class="bkText-red">
        						0
          						</td>
 </tr>
 </table>,
 <table border="0" cellpadding="0" cellspacing="0" id="uryo-suii-dataTb">
 <tr>
 <th scope="row">観測日時</th>
 <td>22:00</td>
 <td>23:00</td>
 <td>00:00</td>
 <td>01:00</td>
 <td>02:00</td>
 <td>03:00</td>
 <td>04:00</td>
 <td>05:00</td>
 <td>06:00</td>
 <td>07:00</td>
 <td>08:00</td>
 <td>09:00</td>
 </tr>
 <tr>
 <th scope="row">1時間雨量</th>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 </tr>
 <tr>
 <th scope="row">累計雨量</th>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 </tr>
 <tr>
 <th scope="row">時間最大雨量</th>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 </tr>
 </table>,
 <table border="0" cellpadding="0" cellspacing="0" id="uryo-suii-dataTb">
 <tr>
 <th scope="row">観測日時</th>
 <td>10:00</td>
 <td>11:00</td>
 <td>12:00</td>
 <td>13:00</td>
 <td>14:00</td>
 <td>15:00</td>
 <td>16:00</td>
 <td>17:00</td>
 <td>18:00</td>
 <td>19:00</td>
 <td>20:00</td>
 <td>21:00</td>
 </tr>
 <tr>
 <th scope="row">1時間雨量</th>
 <td>
        						1
      						</td>
 <td>
        						3
      						</td>
 <td class="bkText-red">
        						5
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 </tr>
 <tr>
 <th scope="row">累計雨量</th>
 <td>
        						1
      						</td>
 <td>
        						4
      						</td>
 <td class="bkText-red">
        						9
      						</td>
 <td>
        						9
      						</td>
 <td>
        						9
      						</td>
 <td>
        						9
      						</td>
 <td>
        						9
      						</td>
 <td>
        						9
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 </tr>
 <tr>
 <th scope="row">時間最大雨量</th>
 <td>

   						</td>
 <td>

   						</td>
 <td class="bkText-red">
        						5
          						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 </tr>
 </table>,
 <table border="0" cellpadding="0" cellspacing="0">
 <tr>
 <th colspan="2" scope="col">雨量</th>
 </tr>
 <tr class="graph-startTd">
 <td class="iconZoon" style="vertical-align:middle;"><img alt="" src="../../img/im/hanrei.JPG"/></td>
 <td>単位時間雨量</td>
 </tr>
 <tr>
 <td class="iconZoon" style="vertical-align:middle;"><img alt="" src="../../img/im/slash_blue.jpg"/></td>
 <td>累計雨量</td>
 </tr>
 <tr>
 <td class="iconZoon" style="vertical-align:middle;">なし</td>
 <td>欠測/未測定</td>
 </tr>
 </table>,
 <table border="0" cellpadding="0" cellspacing="0">
 <tr>
 <th colspan="2" scope="col">観測データ</th>
 </tr>
 <tr class="startTd">
 <td class="bkColor-none" style="text-align:center;">*</td>
 <td>欠測</td>
 </tr>
 <tr>
 <td class="bkColor-none" style="text-align:center;">空白</td>
 <td>未測定</td>
 </tr>
 <tr>
 <td class="bkColor-none bkText-red" style="text-align:center;">赤文字</td>
 <td>時間最大雨量期間</td>
 </tr>
 </table>]

In [60]:
data = []
times_by_1min_upper_row = []
sum_by_1min_upper_row = []
max_by_1min_upper_row = []


for td_data in table[0].findAll('td'):
    data.append(td_data.get_text(strip=True))
times_by_1min = data[0:11]
volume_by_10min = data[12:23]
sum_by_1min = data[24:35]
max_by_1min = data[36:47]

In [61]:
times_by_1min

['20:42',
 '20:43',
 '20:44',
 '20:45',
 '20:46',
 '20:47',
 '20:48',
 '20:49',
 '20:50',
 '20:51',
 '20:52']

In [62]:
volume_by_10min

['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']

In [65]:
sum_by_1min

['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']

In [66]:
max_by_1min

['', '', '', '', '', '', '', '', '', '', '']

In [9]:
table[1]

<table border="0" cellpadding="0" cellspacing="0" id="uryo-suii-dataTb">
<tr>
<th scope="row">観測日時</th>
<td>20:30</td>
<td>20:31</td>
<td>20:32</td>
<td>20:33</td>
<td>20:34</td>
<td>20:35</td>
<td>20:36</td>
<td>20:37</td>
<td>20:38</td>
<td>20:39</td>
<td>20:40</td>
<td>20:41</td>
</tr>
<tr>
<th scope="row">1分間雨量</th>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
</tr>
<tr>
<th scope="row">累計雨量</th>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
</tr>
<tr>
<th scope="row">時間最大雨量</th>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
</tr>
</table>

In [10]:
table[2]

<table border="0" cellpadding="0" cellspacing="0" id="uryo-suii-dataTb">
<tr>
<th scope="row">観測日時</th>
<td>16:50</td>
<td>17:00</td>
<td>17:10</td>
<td>17:20</td>
<td>17:30</td>
<td>17:40</td>
<td>17:50</td>
<td>18:00</td>
<td>18:10</td>
<td>18:20</td>
<td>18:30</td>
<td>18:40</td>
</tr>
<tr>
<th scope="row">10分間雨量</th>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
</tr>
<tr>
<th scope="row">累計雨量</th>
<td>
       						9
     						</td>
<td>
       						9
     						</td>
<td>
       						9
     						</td>
<td>
       						9
     						</td>
<td>
       						9
     						</td>
<td>
       						9
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
</tr>
<tr>
<th scope="row">時間最大雨量</th>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
</tr>
</table>

In [11]:
table[3]

<table border="0" cellpadding="0" cellspacing="0" id="uryo-suii-dataTb">
<tr>
<th scope="row">観測日時</th>
<td>18:50</td>
<td>19:00</td>
<td>19:10</td>
<td>19:20</td>
<td>19:30</td>
<td>19:40</td>
<td>19:50</td>
<td>20:00</td>
<td>20:10</td>
<td>20:20</td>
<td>20:30</td>
<td>20:40</td>
</tr>
<tr>
<th scope="row">10分間雨量</th>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td class="bkText-red">
       						0
     						</td>
<td class="bkText-red">
       						0
     						</td>
<td class="bkText-red">
       						0
     						</td>
<td class="bkText-red">
       						0
     						</td>
<td class="bkText-red">
       						0
     						</td>
<td class="bkText-red">
       						0
     						</td>
</tr>
<tr>
<th scope="row">累計雨量</th>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td class="bkText-red">
       						0
     						</td>
<td class="bkText-red">
       						0
     						</td>
<td class="bkText-red">
       						0
     						</td>
<td class="bkText-red">
       						0
     						</td>
<td class="bkText-red">
       						0
     						</td>
<td class="bkText-red">
       						0
     						</td>
</tr>
<tr>
<th scope="row">時間最大雨量</th>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td class="bkText-red">
       						0
         						</td>
</tr>
</table>

In [12]:
table[4]# 1時間雨量上段

<table border="0" cellpadding="0" cellspacing="0" id="uryo-suii-dataTb">
<tr>
<th scope="row">観測日時</th>
<td>21:00</td>
<td>22:00</td>
<td>23:00</td>
<td>00:00</td>
<td>01:00</td>
<td>02:00</td>
<td>03:00</td>
<td>04:00</td>
<td>05:00</td>
<td>06:00</td>
<td>07:00</td>
<td>08:00</td>
</tr>
<tr>
<th scope="row">1時間雨量</th>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
</tr>
<tr>
<th scope="row">累計雨量</th>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
</tr>
<tr>
<th scope="row">時間最大雨量</th>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
</tr>
</table>

In [13]:
table[5]#1時間雨量下段

<table border="0" cellpadding="0" cellspacing="0" id="uryo-suii-dataTb">
<tr>
<th scope="row">観測日時</th>
<td>09:00</td>
<td>10:00</td>
<td>11:00</td>
<td>12:00</td>
<td>13:00</td>
<td>14:00</td>
<td>15:00</td>
<td>16:00</td>
<td>17:00</td>
<td>18:00</td>
<td>19:00</td>
<td>20:00</td>
</tr>
<tr>
<th scope="row">1時間雨量</th>
<td>
       						0
     						</td>
<td>
       						1
     						</td>
<td>
       						3
     						</td>
<td class="bkText-red">
       						5
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
</tr>
<tr>
<th scope="row">累計雨量</th>
<td>
       						0
     						</td>
<td>
       						1
     						</td>
<td>
       						4
     						</td>
<td class="bkText-red">
       						9
     						</td>
<td>
       						9
     						</td>
<td>
       						9
     						</td>
<td>
       						9
     						</td>
<td>
       						9
     						</td>
<td>
       						9
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
</tr>
<tr>
<th scope="row">時間最大雨量</th>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td class="bkText-red">
       						5
         						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
</tr>
</table>

In [14]:
table[6]

<table border="0" cellpadding="0" cellspacing="0">
<tr>
<th colspan="2" scope="col">雨量</th>
</tr>
<tr class="graph-startTd">
<td class="iconZoon" style="vertical-align:middle;"><img alt="" src="../../img/im/hanrei.JPG"/></td>
<td>単位時間雨量</td>
</tr>
<tr>
<td class="iconZoon" style="vertical-align:middle;"><img alt="" src="../../img/im/slash_blue.jpg"/></td>
<td>累計雨量</td>
</tr>
<tr>
<td class="iconZoon" style="vertical-align:middle;">なし</td>
<td>欠測/未測定</td>
</tr>
</table>

In [15]:
table[7]

<table border="0" cellpadding="0" cellspacing="0">
<tr>
<th colspan="2" scope="col">観測データ</th>
</tr>
<tr class="startTd">
<td class="bkColor-none" style="text-align:center;">*</td>
<td>欠測</td>
</tr>
<tr>
<td class="bkColor-none" style="text-align:center;">空白</td>
<td>未測定</td>
</tr>
<tr>
<td class="bkColor-none bkText-red" style="text-align:center;">赤文字</td>
<td>時間最大雨量期間</td>
</tr>
</table>

In [58]:
tr = table[0].findAll("tr")

[<tr>
 <th scope="row">観測日時</th>
 <td>20:03</td>
 <td>20:04</td>
 <td>20:05</td>
 <td>20:06</td>
 <td>20:07</td>
 <td>20:08</td>
 <td>20:09</td>
 <td>20:10</td>
 <td>20:11</td>
 <td>20:12</td>
 <td>20:13</td>
 <td>20:14</td>
 </tr>, <tr>
 <th scope="row">1分間雨量</th>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 </tr>, <tr>
 <th scope="row">累計雨量</th>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 <td>
        						0
      						</td>
 </tr>, <tr>
 <th scope="row">時間最大雨量</th>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 <td>

   						</td>
 </tr>]

In [53]:
tr[0].findAll("th")

In [43]:
table[0].findAll("td")[0]

In [44]:
for time in table[0].findAll("td"):
    print(time)

<td>20:03</td>
<td>20:04</td>
<td>20:05</td>
<td>20:06</td>
<td>20:07</td>
<td>20:08</td>
<td>20:09</td>
<td>20:10</td>
<td>20:11</td>
<td>20:12</td>
<td>20:13</td>
<td>20:14</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>
       						0
     						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>
<td>

  						</td>